const GITHUB_CONFIG = {
    TOKEN: 'Github_pat_11B5MFRWQ0SSnZ57NkaWll_2AJm5JjIRms8mL4OL4BG10l9OR40yMwI3NNIT1Zv7k0POLPHVGZIRmy1iwW',
    REPO_OWNER: 'USERNAME_ANDA',
    REPO_NAME: 'NAMA_REPO_ANDA',
    FILE_PATH: 'data/notes.json'
};
